### PR TITLE
Patch Update for Faspons.

### PR DESCRIPTION
**Pull request by Shockwave508**
althudcf.txt: Added entry for updated RocketAmmo icon.

zscript.zsc: Added optimized implementation of Adrenaline meter; should render only once now.

### CODE REVIEW

**Comment by Blue-Shadow** [comment]
What about the adrenaline bar's position? Because much like in the other pull request, it's is drawn on top of the air bar. How about moving it down?

**Comment by Shockwave508** [comment]
I will admit, neither of us had even thought about that. But we'll try to work on a solution, so Air Supply and Adrenaline can coexist with no issues.

**Comment by Shockwave508** [comment]
I moved down the Adrenaline bar by 30 pixels, and did the same for the Stamina bar in both Brutal Doom v21 and BD64. Expect a revised pull request shortly.

**Comment by Blue-Shadow** [comment]
The HUD alternates between the air and stamina bars instead of drawing them both at the same time. It gives priority to the air bar. If the air bar isn't drawn, it draws the stamina bar (if the conditions of drawing it are met, of course).

**Pull request closed without merging**
